# Generated by Django 2.2.9 on 2020-04-18 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_logger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logger',
            name='ip_adres',
        ),
    ]
