# Generated by Django 2.2.9 on 2020-04-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0005_remove_logger_ip_adres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='user',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
