# Generated by Django 2.2.9 on 2020-04-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0006_auto_20200418_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggerEditProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveSmallIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
