# Generated by Django 2.2.9 on 2020-04-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0007_loggereditprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
    ]
